### PR TITLE
Update SearchIndex.cs

### PR DESCRIPTION
**Pull request by gokhanbas**
Search Index fixed , reference https://webservices.amazon.com/paapi5/documentation/locale-reference/united-states.html

### CODE REVIEW

**Comment by gokhanbas** [comment]
Search Index fixed , reference https://webservices.amazon.com/paapi5/documentation/locale-reference/united-states.html

**Comment by tinohager** [comment]
I think we need a country-specific implementation for the search index.

**Comment by nauticalcoder** [comment]
> I think we need a country-specific implementation for the search index. Your Implementation is only valid for united-states.

The search indexes in the enumeration don't much the US values either according to the latest Amazon documentation.  For example, the documentation shows a SearchIndex of "Fashion" but unfortunately that is not represented in the SearchIndex enum.

**Comment by BarryHauser** [comment]
Can you merger this im have a issue with the searchindex this will solve all problems

**Pull request closed without merging**
